# Generated by Django 2.2 on 2020-06-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('vote_average', models.FloatField()),
                ('m_id', models.IntegerField()),
                ('overview', models.TextField()),
                ('release_date', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['m_id'],
            },
        ),
    ]
